apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pv0001
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /nfs
    server: 51.254.222.71
  persistentVolumeReclaimPolicy: Recycle
status: {}
