apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: claim-wp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv0001
status: {}

