apiVersion: v1
kind: ImageStream
metadata:
  name: wildfly-90-centos7
spec:
  dockerImageRepository: openshift//wildfly-90-centos7
  tags:
  - annotations:
      description: Wildfly S2I images.
      iconClass: icon-wildfly
      sampleContextDir: kitchensink
      sampleRef: 6.4.x
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:6.4,javaee:6,java:8,xpaas:1.1
      tags: builder,eap,javaee,java,jboss,xpaas
      version: "1.1"
    name: "1.1"
  - annotations:
      description: Wildfly S2I images.
      iconClass: icon-jboss
      sampleContextDir: kitchensink
      sampleRef: 6.4.x
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:6.4,javaee:6,java:8,xpaas:1.2
      tags: builder,eap,javaee,java,jboss,xpaas
      version: "1.2"
    name: "1.2"
status:
  dockerImageRepository: ""
