apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/original-replicas: "1"
    openshift.io/deployer-pod.name: deployment-example-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: deployment-example
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "0"
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"deployment-example","namespace":"test","selfLink":"/oapi/v1/namespaces/test/deploymentconfigs/deployment-example","uid":"23be4318-b71f-11e5-9c11-fa163e865922","resourceVersion":"299","creationTimestamp":"2016-01-09T22:20:07Z","labels":{"app":"deployment-example"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{}},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["deployment-example"],"from":{"kind":"ImageStreamTag","name":"deployment-example:latest"},"lastTriggeredImage":"openshift/deployment-example@sha256:ea9135488f323060cb18ab3ec06286cd49e4b3a611fce1a6a442651ecf421f99"}}],"replicas":1,"selector":{"app":"deployment-example","deploymentconfig":"deployment-example"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"deployment-example","deploymentconfig":"deployment-example"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"deployment-example","image":"openshift/deployment-example@sha256:ea9135488f323060cb18ab3ec06286cd49e4b3a611fce1a6a442651ecf421f99","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}}},"status":{"latestVersion":1,"details":{"causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"ImageStreamTag","name":"deployment-example:latest"}}}]}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: deployment-example
    openshift.io/deployment-config.name: deployment-example
  name: deployment-example-1
spec:
  replicas: 0
  selector:
    app: deployment-example
    deployment: deployment-example-1
    deploymentconfig: deployment-example
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: deployment-example
        openshift.io/deployment.name: deployment-example-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: deployment-example
        deployment: deployment-example-1
        deploymentconfig: deployment-example
    spec:
      containers:
      - image: openshift/deployment-example@sha256:ea9135488f323060cb18ab3ec06286cd49e4b3a611fce1a6a442651ecf421f99
        imagePullPolicy: IfNotPresent
        name: deployment-example
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
